#!/usr/bin/env node
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(ROOT, file), 'utf8');

const index = read('index.html');
const casinoUi = read('buildings/casino/casino-ui.js');
const authGate = read('auth-gate.js');
const auth = read('auth.js');
const server = read('server.js');

assert(index.includes('buildings/casino/casino.css'), 'Casino stylesheet is not loaded');
assert(!index.includes('buildings/casino/casino-agent.js'), 'Legacy estimate agent must not be loaded');
assert(index.includes('buildings/casino/casino-ui.js'), 'Casino UI module is not loaded');
assert(index.includes("makeClickable(g, 'Casino')"), 'Casino is not clickable in the 3D world');
assert(index.includes("'Casino': casino"), 'Casino is absent from the persistent building lookup');
assert(index.includes("_mk(createCasino, 'casino')"), 'Casino is not created during world initialization');
assert(casinoUi.includes("BuildingRegistry.register('Casino'"), 'Casino is absent from BuildingRegistry');
assert(casinoUi.includes('casino-hand-input'), 'Casino is missing mobile hole-card entry');
assert(!casinoUi.includes('casino-stack-input'), 'Casino should not ask Tyler for his stack before the call');
assert(!casinoUi.includes('casinoGtoBaseSetupComplete'), 'Obsolete GTOBase sign-in setup must be removed');
assert(!casinoUi.includes('<iframe'), 'Casino should not embed GTOBase');
assert(casinoUi.includes('casino-answer'), 'Casino is missing the incoming call answer action');
assert(casinoUi.includes('casino-mic'), 'Casino is missing voice input');
assert(casinoUi.includes('/api/openai/transcribe'), 'Casino is not connected to transcription');
assert(casinoUi.includes('/api/openai/tts'), 'Casino is not connected to voice playback');
assert(casinoUi.includes('/api/casino/messages'), 'Casino is not connected to the shared coach channel');
assert(casinoUi.includes('data-casino-role="tyler"'), 'Casino is missing Tyler mode');
assert(casinoUi.includes('data-casino-role="operator"'), 'Casino is missing AI Robot mode');
assert(casinoUi.includes('>AI</button>'), 'Casino operator role must be labeled AI');
assert(casinoUi.includes("sender === roleMode ? 'self' : 'remote'"), 'Casino message sides are not relative to the current viewer');
assert(casinoUi.includes("sender === 'operator' ? 'AI' : 'Tyler'"), 'Casino messages do not use the correct sender labels');
assert(casinoUi.includes('casino-speaker-toggle'), 'Casino is missing the speaker/quiet control');
assert(casinoUi.includes('casino-audio-icon'), 'Casino speaker control is not an icon in the call controls');
assert(casinoUi.includes('selectAudioOutput'), 'Casino does not offer supported private audio output selection');
assert(!casinoUi.includes('CasinoAgent.run'), 'Casino must not generate poker strategy estimates');
assert(casinoUi.includes('startAlwaysOnListening()'), 'Casino does not start continuous listening when the call is answered');
assert(casinoUi.includes('monitorVoiceActivity()'), 'Casino is missing silence-delimited voice activity detection');
assert(casinoUi.includes('now - lastVoiceAt > 900'), 'Casino does not send speech after a short silence');
assert(casinoUi.includes('set Microphone to Allow'), 'Casino is missing mobile permission recovery guidance');
assert(casinoUi.includes('data:audio/wav;base64'), 'Casino does not unlock mobile audio from the Answer gesture');
assert(casinoUi.includes("queueSpeak('What is the action?', `prompt:${tylerCallStartedAt}`)"), 'Casino does not speak the action prompt after Tyler answers');
assert(casinoUi.includes('for (const reply of newReplies)'), 'Casino does not queue every new AI reply for speech');
assert(casinoUi.includes('queueSpeak(reply.content, reply.id)'), 'Casino AI replies are not deduplicated in the speech queue');
assert(!casinoUi.includes('showHumanReply('), 'Casino must not duplicate an AI reply above the chat transcript');
assert(casinoUi.includes('recentSpeechContent.has(normalized)'), 'Casino does not suppress duplicate reply content');
assert(casinoUi.includes('now - queuedAt > 30000'), 'Casino duplicate reply suppression has no bounded window');
assert(casinoUi.includes('generation === speechGeneration ? speak(text, generation)'), 'Casino can play stale speech from another call');
assert(casinoUi.includes('playbackContext.decodeAudioData'), 'Casino does not use its unlocked mobile audio context for replies');
assert(!casinoUi.includes('class="casino-transcript" aria-live'), 'Casino transcript must not duplicate explicit voice playback through a live region');
assert(casinoUi.includes('class="casino-transcript" aria-hidden="true"'), 'Casino transcript must be hidden from competing screen-reader narration');
assert(casinoUi.includes('speed: 1.3'), 'Casino AI voice is not configured for faster playback');
assert(!casinoUi.includes('new SpeechSynthesisUtterance'), 'Casino must use only one speech engine');
assert(casinoUi.includes('tylerCallStartedAt'), 'Casino does not isolate Tyler’s current-call transcript');
assert(casinoUi.includes("roleMode === 'operator' ? 5000 : 200"), 'AI Robot does not load the retained conversation history');
assert(casinoUi.includes('function startRingtone()'), 'Casino does not ring for an incoming call');
assert(casinoUi.includes('ringTimer = setInterval(pulse, 1600)'), 'Casino ringtone does not repeat');
assert(casinoUi.includes('navigator.vibrate([350, 200, 350])'), 'Casino incoming call does not request supported vibration');
assert(casinoUi.includes('function stopRingtone()'), 'Casino cannot stop its ringtone');
assert(casinoUi.includes('aria-label="Hang up"'), 'Casino hang-up button is not accessible');
assert(casinoUi.includes("screen = 'entry';") && casinoUi.includes("tylerCallStartedAt = '';"), 'Hanging up does not return Tyler to hand entry');
assert(!casinoUi.includes('type="password"'), 'Casino must not collect Google passwords');
assert(!casinoUi.toLowerCase().includes('tylerdaviscsatari'), 'Casino UI must not contain private login details');
assert(authGate.includes("'Casino'"), 'Casino is absent from profile permissions');
assert(server.includes("'Casino'"), 'Casino is absent from server-side layout persistence');
assert(auth.includes("return 'Casino'"), 'Casino message API is not permission-gated');
assert(server.includes("pathname === '/api/casino/messages' && req.method === 'GET'"), 'Casino message inbox route is missing');
assert(server.includes("pathname === '/api/casino/messages' && req.method === 'POST'"), 'Casino message send route is missing');
assert(server.includes('CASINO_CHAT_R2_KEY'), 'Casino messages are not persisted to R2');
assert(server.includes('Number(body.speed) || 1'), 'Casino TTS proxy does not forward supported speech speed');
assert(server.includes('messages.slice(-5000)'), 'Casino does not retain the full operator conversation window');

console.log('Casino integration checks passed.');
